.TH DNETINFO 8 "March 30 2006" "DECnet utilities"

.SH NAME
dnetinfo \- DECnet Routing Information
.SH SYNOPSIS
.B dnetinfo [-l]
.SH DESCRIPTION
.PP
.B dnetinfo
is a shell script that queries the dnroute daemon for it's current routes.
The output is very similar to the "SHOW NET/OLD" command on VMS.

.SH OPTIONS
.TP
.I "\-l"
Displays only local neighbour information. This is the default if dnroute is
not running.
.SH SEE ALSO
.BR dnroute "(8), " ip "(8)"
