.TH DNETINFO 8 "March 30 2006" "DECnet utilities"

.SH NAME
dnetinfo \- DECnet Routing Information
.SH SYNOPSIS
.B dnetinfo [-l]
.SH DESCRIPTION
.PP
.B dnetinfo
is a shell script that queries the dnroute daemon for it's current routes.
The output is very similar to the "SHOW NET/OLD" command on VMS.
.br
If dnroute is not running, or you don't have enough privilges to contact it
then it will neatly format the local neighbour table.
.SH OPTIONS
.TP
.I "\-n"
Don't resolve node numbers into names.
.SH SEE ALSO
.BR dnroute "(8)," ip "(8)"
