.TH LATCP 8 "September 10 2002" "LAT Server"

.SH NAME
latcp \- LAT Control Program
.SH SYNOPSIS
.B latcp
[options]
.br
.SH DESCRIPTION
.PP
.B latcp
is the control program for
.B latd(8).


.SS OPTIONS
.TP
.I \-s
Start the LAT daemon. This is the only way to start LAT, you should not
attempt to run latd directly or you may get unexpected behviour.
.B latcp -s
runs the file
.B /etc/latd.conf
as a shell script (using /bin/sh). Any customisations you need to do to the
LAT system should be put in this file as latcp commands. The latcp command
should be invoked using the environment variable $LATCP.
An example latd.conf file is shipped with the package and shown in the man page
.B latd.conf(5).
.br
.B latcp -s
passes any extra switches onto latd itself so you can customise latd this way,
however latd.conf is recommended.

.TP
.I \-h
Halts latd. This will kill any active sessions without warning.

.TP
.I \-A
Create a local LAT service or reverse LAT port.
.br
The syntax for creating a login service is:
.br
latcp -A -a service [-i description] [-r rating] [-s] [-C command] [-u user]
.br
The
.B -s
flag indicates that the service rating is static. Without this the
service rating is regarded as a maximum and will be reduced according
the the load average of the machine.
.br
The
.B -C
flag indicates a command to run when a user connects to the service - by
default this is /bin/login.
.br 
The
.B -u
flag specifies a user to run the above command as. By default this will be root.
.br
The syntax for creating a reverse LAT port is:
.br
latcp -A -p tty -V learned_service [-R rem_port] [-H rem_node] [-Q] [-8]
.br
The tty name should start /dev/lat and must not exist. The
.B -Q
flag indicates that connections to the service is queued. If you
connect to a queued service and it is busy then your connection
will be forced to wait until it is available. You must use this flag
for printer services on DECserver 90L terminal servers, and in this case
the service name must also be empty. NOTE that the
.B -Q
flag is the opposite way round to that on Tru64 Unix(r).
.br
The
.B -8
flag tells latd not to muck about with the data. Normally latd will
transmit a BREAK if a NUL character is typed,
.B -8
disables this behaviour for ports with (eg) printers or modems attached.
.TP
.I \-D
Delete a service or port.
.br
latcp -D -a <service> deletes an advertised service created with
latcp -A -a.
.br
latcp -D -p <tty> deletes a reverse LAT port created with
latcp -A -p

.TP
.I \-i
Change the description of an advertised service
.br
latcp -i <description> -a <service>
.BR
If the description contains spaces or shell metacharacters
you should enclose it in quotes.


.TP
.I \-j
Enables the service responder. This feature is needed for small
terminal servers that do not collect their own service lists.
I currently don't have a list of servers that need this feature.
can anyone help??

.TP
.I \-J
Disables service responder.

.TP
.I \-Y
Purges the list of known services from latd's internal tables.


.TP
.I \-x
Change the rating of an advertised service
.br
latcp -x <rating> [-s] -a <service>
.br
If the -s flag is present the rating is static, otherwise
it is treated as the maximum value and will be decreased according
to the system load average.


.TP
.I \-n
Change the system's current node name (Note this affects latd only,
not DECnet nor TCP/IP)
.br
latcp -n <nodename>


.TP
.I \-r
Change the retransmit limit. This is the maximum number of times
latd will transmit a packet without an acknowlegement. If this
number is exceeded then the connection is closed as it is assumed
that the remote end has gone away.
This value must be between 4 and 120 inclusive, the default is 20.

.TP
.I \-m
Sets the multicast timer (in seconds). This timer determines how
often services are advertised on the LAN. The default is 60 seconds.
This value must be between 10 and 180 inclusive.

.TP
.I \-k
Sets the keepalive timer (in seconds). This is the maximum amount
of time that a connection can be inactive. When this timer expires
an empty message is sent to the remote end. If it does not respond
after <retransmit limit> then the connection is closed. This timer
is reset every time a packet is sent out. This value must be
between 10 and 180 inclusive.


.TP
.I \-d
Displays latd configuration or the learned service table.
.B -d
on it's own will display the latd configuration and the services
that are advertised by this node.
.B -d -l
will display the learned service table. Adding
.B -v
will show the learned service table in a verbose manner.
.B -n
will show the nodes (with MAC addresses) that are associated with
serviceless ports (eg reverse LAT ports to DS90L+ servers).

.TP
.I \-?
Displays help for using the command.

.TP
.I \-G
Add groups to the services advertised. The groups can be numbers
seperated by commas or a range. eg
.br
latcp -G 1,2,3,10-20
.br
Enables groups 1 2 3 and 10 to 20 inclusive.

.TP
.I \-g
Disable groups using syntax as above.

.TP
.I \-U
Add to the list of groups that the server will accept when listening
for services. this affects the services that are available using the
"reverse LAT" feature. See -G for the syntax.
.br
If you are using the "responder" feature it's best make sure that this
group list contains all the groups that are likely to be used on the LAN.

.TP
.I \-u
Remove groups from the user groups list.


.SS SEE ALSO
.BR latd "(8),  "latd.conf "(5), "moprc "(8), " llogin "(1)"
